### ISSUE TITLE
Texture Basics

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/learn-gfx-hal#10]
By the end of this lesson students should be able to

* [x] Use indexed drawing to draw a quad
* [x] Talk about Uniform Buffers
* [x] Upload a texture to the GPU
* [x] Apply the texture to the quad

**Comment by Lokathor** [comment]
Closing in favor of the PR https://github.com/Lokathor/learn-gfx-hal/pull/21
