### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/learn-gfx-hal#4]
The triangle lesson touches on shaders a bit, but we pushed off as much as possible. Now we have to handle all that.

* [x] Talking about how we use "GLSL+magic" to make SPIRV shaders
* [x] Push Constants
* [x] Uniforms
* [x] Pipeline Shader Stages
  * [x] Vertex Shaders: they place a vertex into screen space
    * [ ] Mention using Indexed data to cut down on vertices?
    * [x] Passes any necessary data along to the later stages
    * [x] Attributes!
  * [ ] Tessellation Shader: ?
  * [ ] Geometry Shader: ?
  * [x] Fragment Shader: Turns vertex data into a pixel fragment

By the end of this lesson we want to have a shape on the screen that slowly changes shape and color according to a uniform of the "time since program start". We don't need a full transform matrix, just a box that gets wider and thinner is fine.

**Comment by rukai** [comment]
I reviewed and merged the PR to replace glsl-to-spirv with shaderc in vulkano. (Thanks nlordell!)
So here is my comparison.

## shaderc-rs
*   Acts as a library (no executable)
*   Huge compile times.
*   Need to setup a C++ compiler and python
*   Used by vulkano
*   Currently doesn't handle whitespace in paths https://github.com/google/shaderc-rs/issues/30

## glsl-to-spirv
*   on windows embeds an old and known buggy glslang executable, which is written to disk and then executed.
*   Deprecated and has no source code (except in vulkano's git history)

## Some Future Tool

Ideally shaderc-rs can be replaced with a pure rust implementation some day.
However no one is really working on it.

**Comment by StarArawn** [comment]
@rukai 
3 can be bit of a road block for new people(which is what this tutorial is targeting.) Also the compile times are pretty insane.
It's good to note that there was some discussion in the gfx-hal repo to un-deprecate glsl-to-spirv. Would be nice if it removed the exe embed though.
https://github.com/gfx-rs/gfx/issues/2546

**Comment by Lokathor** [comment]
As part of the "draw a triangle" we (the royal we) have had to set up `shaderc-rs`, so we'll officially be taking that route

**Comment by Lokathor** [comment]
PR in place, diverting any potential conversation there: https://github.com/Lokathor/learn-gfx-hal/pull/17
